# Can test Kaggle up to 5 times a day 

#Feature Extraction

The aim of this jupyter notebook is to build upon the data file extraction made by Amanda. The main idea is to use pre
existing libraries susch as *scikit-learn*. The main goal is to learn the basics, and train a machine learning model
quickly and easily.

In [2]:
# First we will extract the data, and save it to a csv.
# LAMAO ERLEND. HVOR ER DU? hahahhahahaha
# Er hjemmme 😅 skal få H2O, aka autoML til å funke :
# Hva er H20? SMUDE! 
# You go !!


import os
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
%matplotlib inline


from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

In [3]:
train_a = pd.read_parquet('A/train_targets.parquet')
X_train_estimated_a = pd.read_parquet('A/X_train_estimated.parquet')
X_train_observed_a = pd.read_parquet('A/X_train_observed.parquet')
X_test_estimated_a = pd.read_parquet('A/X_test_estimated.parquet')
# X_train_estimated_a.info()

In [4]:
X_train_estimated_a = X_train_estimated_a.drop(["date_calc"],axis=1)

In [5]:
def data_length_matching(train: pd.DataFrame, obs: pd.DataFrame)-> tuple[pd.DataFrame, pd.DataFrame]:
    """
    This function is intended to ensure that both the training data and
    the observed data are sorted, and contain the same number of entries. 
    """

    # Cut the data frames so that their date match.
    obs_feature_test = obs[obs['date_forecast'].isin(train['time'])].sort_values(by=['date_forecast']) # sortert etter datao
    
    # If only one of them has the date ensure that the other also has the same sorting.
    train_feature_test = train[train['time'].isin(obs['date_forecast'])].sort_values(by=['time']) # sortert etter datao

    # Would not the rest ensure this?
    print('If True same length and time stamps')
    print(len(obs_feature_test) == len(train_feature_test))
    print(len(obs_feature_test), len(train_feature_test))

    return train_feature_test, obs_feature_test

def dt64_to_float(dt64):
     year = dt64.astype('M8[Y]')
     days = (dt64 - year).astype('timedelta64[D]')
     year_next = year + np.timedelta64(1, 'Y')
     days_of_year = (year_next.astype('M8[D]') - year.astype('M8[D]')).astype('timedelta64[D]')
     dt_float = 1970 + year.astype(float) + days / (days_of_year)
     return dt_float

### 1.13.1. Removing features with low variance
#+====================================================================================================================+
#| Additional idea: Notice that time of day parameters will probably be provided... Fitting this to a location might  |
#| give us an edge needed to fit a better algorithm for each location...                                              |
#+====================================================================================================================+


This is something 
Use some of scikit learn feature extraction functionality.

* VarianceThreshold

* SelectKBest

* Tree-based feature selection

* Try implementing this into: Pipeline (1.13.6.)

In [7]:
# If changing original variable -- only run once
X_total = pd.concat([X_train_estimated_a, X_train_observed_a], axis = 0)
y, X = data_length_matching(train_a, X_total)
X['date_forecast'] = dt64_to_float(X['date_forecast'].to_numpy())

In [8]:
# y['time'] = dt64_to_float(y['time'].to_numpy())
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
sel.fit_transform(X)

# Get the mask of selected features (True for selected, False for removed)
selected_features_mask = sel.get_support()

# Get the names of removed features
removed_features = [feature for feature, keep in zip(X.columns, selected_features_mask) if not keep]

# Print the names of removed features
print("Removed features:", removed_features)

Removed features: ['air_density_2m:kgm3', 'dew_or_rime:idx', 'elevation:m', 'fresh_snow_1h:cm', 'fresh_snow_3h:cm', 'fresh_snow_6h:cm', 'precip_5min:mm', 'precip_type_5min:idx', 'rain_water:kgm2', 'snow_density:kgm3', 'snow_drift:idx', 'snow_melt_10min:mm', 'snow_water:kgm2', 'super_cooled_liquid_water:kgm2', 'wind_speed_w_1000hPa:ms']


### 1.13.2. Univariate feature selection

In [9]:
# If changing original variable -- only run once
X = X.drop(removed_features, axis=1) 
X = X.fillna(0)
# y = y.drop('time', axis=1)
y = y['pv_measurement'].ravel()

In [12]:
X_new = SelectKBest(f_regression, k=5).fit_transform(X, y)

print("This is x-new")
print(X_new)

This is x-new
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
from sklearn.feature_selection import SelectKBest, f_regression

# Fit the SelectKBest method and transform the data
selector = SelectKBest(f_regression, k=5)
X_new = selector.fit_transform(X, y)

# Get the mask of selected features (True for selected, False for removed)
selected_features_mask = selector.get_support()

# Get the names of removed features
removed_features = [feature for feature, keep in zip(X.columns, ~selected_features_mask)]

# Print the names of removed features
print("Removed features:", removed_features)

# Print the selected features (X_new)
print("This is X_new")
print(X_new)


Removed features: ['date_forecast', 'absolute_humidity_2m:gm3', 'ceiling_height_agl:m', 'clear_sky_energy_1h:J', 'clear_sky_rad:W', 'cloud_base_agl:m', 'dew_point_2m:K', 'diffuse_rad:W', 'diffuse_rad_1h:J', 'direct_rad:W', 'direct_rad_1h:J', 'effective_cloud_cover:p', 'fresh_snow_12h:cm', 'fresh_snow_24h:cm', 'is_day:idx', 'is_in_shadow:idx', 'msl_pressure:hPa', 'pressure_100m:hPa', 'pressure_50m:hPa', 'prob_rime:p', 'relative_humidity_1000hPa:p', 'sfc_pressure:hPa', 'snow_depth:cm', 'sun_azimuth:d', 'sun_elevation:d', 't_1000hPa:K', 'total_cloud_cover:p', 'visibility:m', 'wind_speed_10m:ms', 'wind_speed_u_10m:ms', 'wind_speed_v_10m:ms']
This is X_new
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
from sklearn.feature_selection import SelectKBest, f_regression

# Create a SelectKBest instance with the f_regression method and k=5 (to select 5 best features)
selector = SelectKBest(f_regression, k=5)

# Fit the SelectKBest instance on your data (X and y) to select the best features
X_new = selector.fit_transform(X, y)

# Get the mask of selected features (True for selected, False for removed)
selected_features_mask = selector.get_support()

# Get the names of removed features (features not selected)
removed_features = [feature for feature, keep in zip(X.columns, ~selected_features_mask)]

# Print the names of removed features
print("Removed features:", removed_features)


Removed features: ['date_forecast', 'absolute_humidity_2m:gm3', 'ceiling_height_agl:m', 'clear_sky_energy_1h:J', 'clear_sky_rad:W', 'cloud_base_agl:m', 'dew_point_2m:K', 'diffuse_rad:W', 'diffuse_rad_1h:J', 'direct_rad:W', 'direct_rad_1h:J', 'effective_cloud_cover:p', 'fresh_snow_12h:cm', 'fresh_snow_24h:cm', 'is_day:idx', 'is_in_shadow:idx', 'msl_pressure:hPa', 'pressure_100m:hPa', 'pressure_50m:hPa', 'prob_rime:p', 'relative_humidity_1000hPa:p', 'sfc_pressure:hPa', 'snow_depth:cm', 'sun_azimuth:d', 'sun_elevation:d', 't_1000hPa:K', 'total_cloud_cover:p', 'visibility:m', 'wind_speed_10m:ms', 'wind_speed_u_10m:ms', 'wind_speed_v_10m:ms']
